NXP-18724 redirect nuxeoctl warns and errors to stderr

diff --git a/nuxeo-distribution/nuxeo-server-tomcat/src/main/resources/tomcat/bin/nuxeoctl b/nuxeo-distribution/nuxeo-server-tomcat/src/main/resources/tomcat/bin/nuxeoctl
--- a/nuxeo-distribution/nuxeo-server-tomcat/src/main/resources/tomcat/bin/nuxeoctl
+++ b/nuxeo-distribution/nuxeo-server-tomcat/src/main/resources/tomcat/bin/nuxeoctl
@@ -39,11 +39,11 @@ set -- "${cmdargs[@]}"
 
 ## Helper functions
 warn() {
-  echo "WARNING: $*"
+  echo "WARNING: $*" 1>&2
 }
 
 die() {
-  echo "ERROR: $*"
+  echo "ERROR: $*" 1>&2
   exit 1
 }
 
