NXP-18023: Java 8 update 40+ is required

diff --git a/nuxeo-distribution/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl b/nuxeo-distribution/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
--- a/nuxeo-distribution/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
+++ b/nuxeo-distribution/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
@@ -1,11 +1,11 @@
 #!/bin/bash
 ##
-## (C) Copyright 2010-2014 Nuxeo SA (http://nuxeo.com/) and contributors.
+## (C) Copyright 2010-2015 Nuxeo SA (http://nuxeo.com/) and contributors.
 ##
 ## All rights reserved. This program and the accompanying materials
 ## are made available under the terms of the GNU Lesser General Public License
 ## (LGPL) version 2.1 which accompanies this distribution, and is available at
-## http://www.gnu.org/licenses/lgpl.html
+## http://www.gnu.org/licenses/lgpl-2.1.html
 ##
 ## This library is distributed in the hope that it will be useful,
 ## but WITHOUT ANY WARRANTY; without even the implied warranty of
@@ -98,9 +98,9 @@ PATH="$JAVA_HOME/bin:$PATH"
 # Check Java
 : ${REQUIRED_JAVA_VERSION:=1.8}
 # Check 'java' bin
-which java >/dev/null 2>&1 || die "Nuxeo requires Java $REQUIRED_JAVA_VERSION+. No java command detected in the PATH (including JAVA_HOME)."
+command -v $JAVA >/dev/null 2>&1 || die "Nuxeo requires Java $REQUIRED_JAVA_VERSION+. No $JAVA command detected in the PATH (including JAVA_HOME)."
 # Check Java version
-JAVA_VERSION=`java -version 2>&1 | awk -F '"' '/version/{print $2}'`
+JAVA_VERSION=`$JAVA -version 2>&1 | awk -F '"' '/version/{print $2}'`
 if [ "$JAVA_VERSION" \< "$REQUIRED_JAVA_VERSION" ]; then
   die "Nuxeo requires Java $REQUIRED_JAVA_VERSION+ (detected $JAVA_VERSION)"
 fi
