fix issue with h2 which is always relative to default data dir even with absolute value

diff --git a/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl b/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
--- a/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
+++ b/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
@@ -325,28 +325,36 @@ check_old_paths() {
   # Check JBoss paths
   if [ "$jboss" = "true" ] && \
     ( [ -e "$NUXEO_HOME"/server/default/data/h2 ] || [ -e "$NUXEO_HOME"/server/default/data/derby ] ); then
-    echo ERROR: Deprecated paths used \(NXP-5370, NXP-5460\).
+    echo "ERROR: Deprecated paths used (NXP-5370, NXP-5460)."
     die "Please move 'h2' and 'derby' directories from \"$NUXEO_HOME/server/default/data/\" to \"$DATA_DIR\""
     exit 1
   fi
   if [ "$jboss" = "true" ] && [ -e "$NUXEO_HOME"/server/default/data/NXRuntime/binaries ]; then
-    echo ERROR: Deprecated paths used \(NXP-5460\).
+    echo "ERROR: Deprecated paths used (NXP-5460)."
     die "Please move 'binaries' directory from \"$NUXEO_HOME/server/default/data/NXRuntime/binaries\" to \"$DATA_DIR/binaries\""
     exit 1
   fi
   if [ "$jboss" = "true" ] && [ -e "$DATA_DIR"/NXRuntime/binaries ]; then
-    echo ERROR: Deprecated paths used \(NXP-5460\).
+    echo "ERROR: Deprecated paths used (NXP-5460)."
     die "Please move 'binaries' directory from \"$DATA_DIR/NXRuntime/binaries\" to \"$DATA_DIR/binaries\""
     exit 1
   fi
   # Check Tomcat paths
-  if [ "$jboss" = "true" ] && \
-    ( [ -e "$NUXEO_HOME"/vcsh2repo ] ); then
-    echo ERROR: Deprecated paths used \(NXP-5370, NXP-5460\).
-    die "Please rename 'vcsh2repo' directory from \"$DATA_DIR/h2/vcsh2repo\" to \"$DATA_DIR/h2/nuxeo\""
+  if [ "$tomcat" = "true" ] && \
+    ( [ -e "$NUXEO_HOME"/nxserver/data/vcsh2repo ] ); then
+    echo "ERROR: Deprecated paths used (NXP-5370, NXP-5460)."
+    die "Please rename 'vcsh2repo' directory from \"$NUXEO_HOME/nxserver/data/vcsh2repo\" to \"$DATA_DIR/h2/nuxeo\""
     exit 1
   fi
-
+  if [ "$tomcat" = "true" ] && \
+    ( [ -e "$NUXEO_HOME"/nxserver/data/derby/nxsqldirectory ] ); then
+    echo "ERROR: Deprecated paths used (NXP-5370, NXP-5460)."
+    echo "ERROR: It is not possible to migrate derby data."
+    die "Please remove 'nx*' directories from \"$NUXEO_HOME/nxserver/data/derby/\"
+or edit templates/default/conf/Catalina/localhost/nuxeo.xml
+following http://hg.nuxeo.org/nuxeo/nuxeo-distribution/raw-file/5.3.2/nuxeo-distribution-resources/src/main/resources/templates-tomcat/default/conf/Catalina/localhost/nuxeo.xml"
+    exit 1
+  fi
 }
 
 # Check if nuxeo.conf used has not changed since last run (if not first run)
@@ -423,7 +431,7 @@ stop() {
         sleep 1 || exit 1
       else
         rm "$PID"
-        echo Nuxeo stopped.
+        echo "Nuxeo stopped."
         return 0
       fi
     done
