remove tabs

diff --git a/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl b/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
--- a/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
+++ b/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
@@ -10,12 +10,12 @@
 # Helper functions
 
 warn() {
-	echo "WARNING: $*"
+  echo "WARNING: $*"
 }
 
 die() {
-	echo "ERROR: $*"
-	exit 1
+  echo "ERROR: $*"
+  exit 1
 }
 
 
@@ -26,9 +26,9 @@ darwin=false
 linux=false
 
 case "`uname`" in
-	CYGWIN*) cygwin=true;;
-	Darwin*) darwin=true;;
-	Linux) linux=true;;
+  CYGWIN*) cygwin=true;;
+  Darwin*) darwin=true;;
+  Linux) linux=true;;
 esac
 
 
@@ -38,13 +38,13 @@ PRG="$0"
 
 # follow symlinks
 while [ -h "$PRG" ]; do
-	ls=`ls -ld "$PRG"`
-	link=`expr "$ls" : '.*-> \(.*\)$'`
-	if expr "$link" : '/.*' > /dev/null; then
-		PRG="$link"
-	else
-		PRG=`dirname "$PRG"`/"$link"
-	fi
+  ls=`ls -ld "$PRG"`
+  link=`expr "$ls" : '.*-> \(.*\)$'`
+  if expr "$link" : '/.*' > /dev/null; then
+    PRG="$link"
+  else
+    PRG=`dirname "$PRG"`/"$link"
+  fi
 done
 
 DIRNAME=`dirname "$PRG"`
@@ -55,51 +55,51 @@ PROGNAME=`basename "$PRG"`
 # We can't just source it as sh/bash don't like dots in variable names
 
 if [ "x$NUXEO_CONF" = "x" ]; then
-	NUXEO_CONF="$DIRNAME/nuxeo.conf"
+  NUXEO_CONF="$DIRNAME/nuxeo.conf"
 fi
 if [ -r "$NUXEO_CONF" ]; then
-	while read confline
-	do
-		if [ "x$confline" = "x" ]; then
-			continue
-		fi
-		if [[ "$confline" == \#* ]]; then
-			continue
-		fi
-		key="$(echo $confline | cut -d= -f1)"
-		value="$(echo $confline | cut -d= -f2-)"
-		if [[ "$key" == "nuxeo.log.dir" ]]; then
-			read -r LOG_DIR <<< $value
-		fi
-		if [[ "$key" == "nuxeo.pid.dir" ]]; then
-			read -r PID_DIR <<< $value
-		fi
-		if [[ "$key" == "nuxeo.data.dir" ]]; then
-			read -r DATA_DIR <<< $value
-		fi
-		if [[ "$key" == "nuxeo.tmp.dir" ]]; then
-			read -r TMP_DIR <<< $value
-		fi
-		if [[ "$key" == "nuxeo.bind.address" ]]; then
-			read -r BIND_ADDRESS <<< $value
-		fi
-		if [[ "$key" == *.* ]]; then
-			continue
-		fi
-		eval "$key=\"$value\""
-	done < $NUXEO_CONF
+  while read confline
+  do
+    if [ "x$confline" = "x" ]; then
+      continue
+    fi
+    if [[ "$confline" == \#* ]]; then
+      continue
+    fi
+    key="$(echo $confline | cut -d= -f1)"
+    value="$(echo $confline | cut -d= -f2-)"
+    if [[ "$key" == "nuxeo.log.dir" ]]; then
+      read -r LOG_DIR <<< $value
+    fi
+    if [[ "$key" == "nuxeo.pid.dir" ]]; then
+      read -r PID_DIR <<< $value
+    fi
+    if [[ "$key" == "nuxeo.data.dir" ]]; then
+      read -r DATA_DIR <<< $value
+    fi
+    if [[ "$key" == "nuxeo.tmp.dir" ]]; then
+      read -r TMP_DIR <<< $value
+    fi
+    if [[ "$key" == "nuxeo.bind.address" ]]; then
+      read -r BIND_ADDRESS <<< $value
+    fi
+    if [[ "$key" == *.* ]]; then
+      continue
+    fi
+    eval "$key=\"$value\""
+  done < $NUXEO_CONF
 fi
 
 
 # For Cygwin, ensure paths are in UNIX format before anything is touched
 
 if [ "$cygwin" = "true" ]; then
-	[ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
-	[ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
-	[ -n "$JBOSS_HOME" ] && JBOSS_HOME=`cygpath --unix "$JBOSS_HOME"`
-	[ -n "$CATALINA_HOME" ] && CATALINA_HOME=`cygpath --unix "$CATALINA_HOME"`
-	[ -n "$JETTY_HOME" ] && JETTY_HOME=`cygpath --unix "$JETTY_HOME"`
-	[ -n "$NUXEO_HOME" ] && NUXEO_HOME=`cygpath --unix "$NUXEO_HOME"`
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
+  [ -n "$JBOSS_HOME" ] && JBOSS_HOME=`cygpath --unix "$JBOSS_HOME"`
+  [ -n "$CATALINA_HOME" ] && CATALINA_HOME=`cygpath --unix "$CATALINA_HOME"`
+  [ -n "$JETTY_HOME" ] && JETTY_HOME=`cygpath --unix "$JETTY_HOME"`
+  [ -n "$NUXEO_HOME" ] && NUXEO_HOME=`cygpath --unix "$NUXEO_HOME"`
 fi
 
 
@@ -127,11 +127,11 @@ PATH="$JAVA_HOME/bin:$PATH"
 
 # Setup NUXEO_HOME
 if [ -z "$NUXEO_HOME" ]; then
-	if [ -n "$JBOSS_HOME" ]; then NUXEO_HOME="$JBOSS_HOME"
-	elif [ -n "$CATALINA_HOME" ]; then NUXEO_HOME="$CATALINA_HOME"
-	elif [ -n "$JETTY_HOME" ]; then NUXEO_HOME="$JETTY_HOME"
-	else NUXEO_HOME=`cd "$DIRNAME"/..; pwd`
-	fi
+  if [ -n "$JBOSS_HOME" ]; then NUXEO_HOME="$JBOSS_HOME"
+  elif [ -n "$CATALINA_HOME" ]; then NUXEO_HOME="$CATALINA_HOME"
+  elif [ -n "$JETTY_HOME" ]; then NUXEO_HOME="$JETTY_HOME"
+  else NUXEO_HOME=`cd "$DIRNAME"/..; pwd`
+  fi
 fi
 
 
@@ -140,33 +140,33 @@ fi
 # LOG_DIR
 
 if [ -z "$LOG_DIR" ]; then
-	LOG_DIR="$NUXEO_HOME/log"
+  LOG_DIR="$NUXEO_HOME/log"
 elif [[ "$LOG_DIR" != /* ]]; then
-	LOG_DIR="$NUXEO_HOME/$LOG_DIR"
+  LOG_DIR="$NUXEO_HOME/$LOG_DIR"
 fi
 LOG="$LOG_DIR/console.log"
 
 # PID_DIR
 
 if [ -z "$PID_DIR" ]; then
-	PID_DIR="$LOG_DIR"
+  PID_DIR="$LOG_DIR"
 elif [[ "$PID_DIR" != /* ]]; then
-	PID_DIR="$NUXEO_HOME/$PID_DIR"
+  PID_DIR="$NUXEO_HOME/$PID_DIR"
 fi
 PID="$PID_DIR/nuxeo.pid"
 
 
 # Where possible, increase the maximum number of file descriptors
 if [ "$cygwin" = "false" ]; then
-	MAX_FD_LIMIT=`ulimit -H -n`
-	if [ $? -eq 0 ]; then
-		if [ "$darwin" = "true" ] && [ "$MAX_FD_LIMIT" = "unlimited" ]; then
-			MAX_FD_LIMIT=`sysctl -n kern.maxfilesperproc`
-		fi
-		ulimit -n $MAX_FD_LIMIT
-	else
-		warn "Could not get system maximum file descriptor limit: $MAX_FD_LIMIT"
-	fi
+  MAX_FD_LIMIT=`ulimit -H -n`
+  if [ $? -eq 0 ]; then
+    if [ "$darwin" = "true" ] && [ "$MAX_FD_LIMIT" = "unlimited" ]; then
+      MAX_FD_LIMIT=`sysctl -n kern.maxfilesperproc`
+    fi
+    ulimit -n $MAX_FD_LIMIT
+  else
+    warn "Could not get system maximum file descriptor limit: $MAX_FD_LIMIT"
+  fi
 fi
 
 
@@ -177,22 +177,22 @@ JAVA_OPTS="$JAVA_OPTS -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true"
 # If -server not set in JAVA_OPTS, set it, if supported
 SERVER_SET=`echo $JAVA_OPTS | grep "\-server"`
 if [ "x$SERVER_SET" = "x" ]; then
-	# Check for SUN(tm) JVM w/ HotSpot support
-	if [ "x$HAS_HOTSPOT" = "x" ]; then
-		HAS_HOTSPOT=`"$JAVA" -version 2>&1 | grep -i HotSpot`
-	fi
-	# Enable -server if we have Hotspot, unless we can't
-	if [ "x$HAS_HOTSPOT" != "x" ]; then
-		# MacOS does not support -server flag
-		if [ "$darwin" != "true" ]; then
-			JAVA_OPTS="-server $JAVA_OPTS"
-		fi
-	fi
+  # Check for SUN(tm) JVM w/ HotSpot support
+  if [ "x$HAS_HOTSPOT" = "x" ]; then
+    HAS_HOTSPOT=`"$JAVA" -version 2>&1 | grep -i HotSpot`
+  fi
+  # Enable -server if we have Hotspot, unless we can't
+  if [ "x$HAS_HOTSPOT" != "x" ]; then
+    # MacOS does not support -server flag
+    if [ "$darwin" != "true" ]; then
+      JAVA_OPTS="-server $JAVA_OPTS"
+    fi
+  fi
 fi
 
 # Bind address
 if [ "x$BIND_ADDRESS" = "x" ]; then
-	BIND_ADDRESS=0.0.0.0
+  BIND_ADDRESS=0.0.0.0
 fi
 
 # Application server detection
@@ -222,42 +222,42 @@ fi
 if [ "$jboss" = "true" ]; then
 
   # TODO: remove since Nuxeo is no more compliant with Java 1.5
-	# Fix JRE 1.5/1.6 issue with script-api.jar
-	IS_JRE_6=`"$JAVA" -version 2>&1|grep "version \"1\.6"`
-	NUXEO_EAR="$NUXEO_HOME/server/default/deploy/nuxeo.ear"
-	JAVA5_APIS="script-api"
-	for java5_api in $JAVA5_APIS;
-	do
-  	if [ ! -z "$IS_JRE_6" ]; then
-  		#echo "Java 1.6 detected"
-  		JAVA5_API=`ls "$NUXEO_EAR"/lib/$java5_api*.jar 2>/dev/null || echo "null"`
-  		if [ -f "$JAVA5_API" ]; then
-  			echo "Moving $JAVA5_API out of classpath (already provided by Java6)"
-  			mkdir "$NUXEO_EAR"/lib-jre1.5/ 2>/dev/null
-  			mv "$JAVA5_API" "$NUXEO_EAR"/lib-jre1.5/
-  		fi
-  	else
-  		#echo "Assumed Java 1.5"
-  		JAVA5_API=`ls "$NUXEO_EAR"/lib/$java5_api*.jar 2>/dev/null || echo "null"`
-  		if [ ! -f "$JAVA5_API" ]; then
-  			echo "Moving $JAVA5_API into classpath"
-  			mv "$NUXEO_EAR"/lib-jre1.5/$java5_api*.jar "$NUXEO_EAR"/lib/ 2>/dev/null || \
-  			echo "Missing $java5_api in $NUXEO_EAR/lib/ or $NUXEO_EAR/lib-jre1.5/" >&2
-  		fi
-  	fi
-	done
+  # Fix JRE 1.5/1.6 issue with script-api.jar
+  IS_JRE_6=`"$JAVA" -version 2>&1|grep "version \"1\.6"`
+  NUXEO_EAR="$NUXEO_HOME/server/default/deploy/nuxeo.ear"
+  JAVA5_APIS="script-api"
+  for java5_api in $JAVA5_APIS;
+  do
+  if [ ! -z "$IS_JRE_6" ]; then
+    #echo "Java 1.6 detected"
+    JAVA5_API=`ls "$NUXEO_EAR"/lib/$java5_api*.jar 2>/dev/null || echo "null"`
+    if [ -f "$JAVA5_API" ]; then
+      echo "Moving $JAVA5_API out of classpath (already provided by Java6)"
+      mkdir "$NUXEO_EAR"/lib-jre1.5/ 2>/dev/null
+      mv "$JAVA5_API" "$NUXEO_EAR"/lib-jre1.5/
+    fi
+  else
+    #echo "Assumed Java 1.5"
+    JAVA5_API=`ls "$NUXEO_EAR"/lib/$java5_api*.jar 2>/dev/null || echo "null"`
+    if [ ! -f "$JAVA5_API" ]; then
+      echo "Moving $JAVA5_API into classpath"
+      mv "$NUXEO_EAR"/lib-jre1.5/$java5_api*.jar "$NUXEO_EAR"/lib/ 2>/dev/null || \
+      echo "Missing $java5_api in $NUXEO_EAR/lib/ or $NUXEO_EAR/lib-jre1.5/" >&2
+    fi
+  fi
+  done
 
   # Paths and specific options
-	TMP_OVERRIDE="false"
-	if [ -n "$TMP_DIR" ]; then
-		TMP_OVERRIDE="true"
-	fi
-	TMP_DIR=${TMP_DIR:-server/default/tmp}
+  TMP_OVERRIDE="false"
+  if [ -n "$TMP_DIR" ]; then
+    TMP_OVERRIDE="true"
+  fi
+  TMP_DIR=${TMP_DIR:-server/default/tmp}
 
-	DATA_DIR=${DATA_DIR:-server/default/data/NXRuntime/data}
-	JBOSS_DATA_DIR=${JBOSS_DATA_DIR:-"$NUXEO_HOME"/server/default/data}
-	NUXEO_CLASSPATH="$CLASSPATH:$jbossjar"
-	NUXEO_ENDORSED="$NUXEO_HOME/lib/endorsed"
+  DATA_DIR=${DATA_DIR:-server/default/data/NXRuntime/data}
+  JBOSS_DATA_DIR=${JBOSS_DATA_DIR:-"$NUXEO_HOME"/server/default/data}
+  NUXEO_CLASSPATH="$CLASSPATH:$jbossjar"
+  NUXEO_ENDORSED="$NUXEO_HOME/lib/endorsed"
   NUXEO_BOOTJAR_PATH="$NUXEO_HOME/server/default/lib/*"
   LOG4J_CONF="file:$NUXEO_HOME/server/default/conf/jboss-log4j.xml"
 
@@ -265,11 +265,11 @@ if [ "$jboss" = "true" ]; then
 # TOMCAT
 #
 elif [ "$tomcat" = "true" ]; then
-	# Paths and specific options
+  # Paths and specific options
   TMP_DIR=${TMP_DIR:-tmp}
   CATALINA_TEMP=${CATALINA_TEMP:-$TMP_DIR}
-	DATA_DIR=${DATA_DIR:-nxserver/data}
-	NUXEO_CLASSPATH="$CLASSPATH:$tomcatjar"
+  DATA_DIR=${DATA_DIR:-nxserver/data}
+  NUXEO_CLASSPATH="$CLASSPATH:$tomcatjar"
   NUXEO_BOOTJAR_PATH="$NUXEO_HOME/nxserver/bundles/*:$NUXEO_HOME/lib/*"
   TMP_DIR=${TMP_DIR:-$NUXEO_HOME/temp}
   LOG4J_CONF="file:$NUXEO_HOME/lib/log4j.xml"
@@ -278,17 +278,17 @@ elif [ "$tomcat" = "true" ]; then
 # JETTY
 #
 elif [ "$jetty" = "true" ]; then
-	# Paths and specific options
-	TMP_DIR=${TMP_DIR:-tmp}
-	DATA_DIR=${DATA_DIR:-data}
-	NXC_VERSION=`basename $jettyjar | cut -d"-" -f4-`
-	NUXEO_CLASSPATH="$CLASSPATH:$jettyjar"
+  # Paths and specific options
+  TMP_DIR=${TMP_DIR:-tmp}
+  DATA_DIR=${DATA_DIR:-data}
+  NXC_VERSION=`basename $jettyjar | cut -d"-" -f4-`
+  NUXEO_CLASSPATH="$CLASSPATH:$jettyjar"
   NUXEO_BOOTJAR_PATH="$NUXEO_HOME/bundles/*:$NUXEO_HOME/lib/*"
-	NUXEO_BUNDLES="$NUXEO_HOME/bundles/.:$NUXEO_HOME/lib/.:$NUXEO_HOME/config"
-	JAVA_OPTS="$JAVA_OPTS -Djava.rmi.server.RMIClassLoaderSpi=org.nuxeo.runtime.launcher.NuxeoRMIClassLoader"
-	JAVA_OPTS="$JAVA_OPTS -Dsun.lang.ClassLoader.allowArraySyntax=true"
-	JAVA_OPTS="$JAVA_OPTS -Dderby.system.home=$DATA_DIR/derby"
-	JAVA_OPTS="$JAVA_OPTS -Dorg.nuxeo.launcher.libdirs=lib"
+  NUXEO_BUNDLES="$NUXEO_HOME/bundles/.:$NUXEO_HOME/lib/.:$NUXEO_HOME/config"
+  JAVA_OPTS="$JAVA_OPTS -Djava.rmi.server.RMIClassLoaderSpi=org.nuxeo.runtime.launcher.NuxeoRMIClassLoader"
+  JAVA_OPTS="$JAVA_OPTS -Dsun.lang.ClassLoader.allowArraySyntax=true"
+  JAVA_OPTS="$JAVA_OPTS -Dderby.system.home=$DATA_DIR/derby"
+  JAVA_OPTS="$JAVA_OPTS -Dorg.nuxeo.launcher.libdirs=lib"
   LOG4J_CONF="file:$NUXEO_HOME/config/log4j.xml"
 
 #
@@ -296,7 +296,7 @@ elif [ "$jetty" = "true" ]; then
 #
 
 else
-	die "Oops, something went very wrong, I'm not supposed to be here !"
+  die "Oops, something went very wrong, I'm not supposed to be here !"
 fi
 
 if [ "$cygwin" = "true" ]; then
@@ -318,9 +318,9 @@ fi
 
 # Set absolute path for tmp directory if any
 if [ -n "$TMP_DIR" ]; then
-	if [[ "$TMP_DIR" != /* ]]; then
-		TMP_DIR="$NUXEO_HOME/$TMP_DIR"
-	fi
+  if [[ "$TMP_DIR" != /* ]]; then
+    TMP_DIR="$NUXEO_HOME/$TMP_DIR"
+  fi
 fi
 
 # Check old paths (NXP-5370, NXP-5460)
@@ -366,31 +366,31 @@ generate_configuration() {
 }
 
 checkalive() {
-	if [ ! -r "$PID" ]; then
-		return 1
-	fi
-	MYPID=`cat "$PID"`
-	JPS=`jps -v | grep "nuxeo.home=$NUXEO_HOME" | cut -f1 -d" " | grep $MYPID`
-	if [ "x$JPS" = "x" ]; then
-		return 1
-	else
-		return 0
-	fi
+  if [ ! -r "$PID" ]; then
+    return 1
+  fi
+  MYPID=`cat "$PID"`
+  JPS=`jps -v | grep "nuxeo.home=$NUXEO_HOME" | cut -f1 -d" " | grep $MYPID`
+  if [ "x$JPS" = "x" ]; then
+    return 1
+  else
+    return 0
+  fi
 }
 
 createdirs() {
-	if [ ! -d "$LOG_DIR" ]; then
-		mkdir -p "$LOG_DIR"
-	fi
-	if [ ! -d "$PID_DIR" ]; then
-		mkdir -p "$PID_DIR"
-	fi
-	if [ ! -z "$DATA_DIR" ] && [ ! -d "$DATA_DIR" ]; then
-		mkdir -p "$DATA_DIR"
-	fi
-	if [ ! -z "$TMP_DIR" ] && [ ! -d "$TMP_DIR" ]; then
-		mkdir -p "$TMP_DIR"
-	fi
+  if [ ! -d "$LOG_DIR" ]; then
+    mkdir -p "$LOG_DIR"
+  fi
+  if [ ! -d "$PID_DIR" ]; then
+    mkdir -p "$PID_DIR"
+  fi
+  if [ ! -z "$DATA_DIR" ] && [ ! -d "$DATA_DIR" ]; then
+    mkdir -p "$DATA_DIR"
+  fi
+  if [ ! -z "$TMP_DIR" ] && [ ! -d "$TMP_DIR" ]; then
+    mkdir -p "$TMP_DIR"
+  fi
 }
 
 stop() {
@@ -563,25 +563,25 @@ if check_nuxeo_conf; then
 fi
 
 case "$1" in
-	status)
-		if checkalive; then
-			echo "Nuxeo is running with pid `cat \"$PID\"`"
-		else
-			echo "Nuxeo is not running."
-		fi
-		;;
+  status)
+    if checkalive; then
+      echo "Nuxeo is running with pid `cat \"$PID\"`"
+    else
+      echo "Nuxeo is not running."
+    fi
+    ;;
   startbg)
-	  startbg
-		;;
-	start)
-	  start
-	  ;;
+    startbg
+    ;;
+  start)
+    start
+    ;;
   console)
     console
-		;;
+    ;;
   stop)
-	  stop
-		;;
+    stop
+    ;;
   restart)
     stop
     start
@@ -589,7 +589,7 @@ case "$1" in
   configure)
     generate_configuration console
     ;;
-	*)
-		echo "Usage: nuxeoctl (startbg|start|console|stop|status|configure)"
-		;;
+  *)
+    echo "Usage: nuxeoctl (startbg|start|console|stop|status|configure)"
+    ;;
 esac
