prepare release 5.4.3-20110729

diff --git a/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl b/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
--- a/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
+++ b/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
@@ -1,6 +1,6 @@
 #!/bin/bash
 ##
-## (C) Copyright 2010 Nuxeo SAS (http://nuxeo.com/) and contributors.
+## (C) Copyright 2010-2011 Nuxeo SAS (http://nuxeo.com/) and contributors.
 ##
 ## All rights reserved. This program and the accompanying materials
 ## are made available under the terms of the GNU Lesser General Public License
@@ -36,30 +36,6 @@ die() {
 }
 
 
-
-## Helper functions
-warn() {
-  echo "WARNING: $*"
-}
-
-die() {
-  echo "ERROR: $*"
-  exit 1
-}
-
-
-
-## Helper functions
-warn() {
-  echo "WARNING: "
-}
-
-die() {
-  echo "ERROR: "
-  exit 1
-}
-
-
 ## OS detection
 cygwin=false
 darwin=false
@@ -70,8 +46,8 @@ case "`uname`" in
   #Linux) linux=true;;
 esac
 
-
-
+## Empty $GREP_OPTIONS to prevent some undesirable behaviors
+GREP_OPTIONS=""
 
 ## Setup the JVM (find JAVA_HOME if undefined; use JAVA if defined)
 while read line; do
@@ -129,8 +105,8 @@ fi
 if ! [[ "x$JAVA_OPTS" =~ -server ]]; then
   # Enable -server if we have HotSpot
   if [[ x`"$JAVA" -version 2>&1` =~ HotSpot ]]; then
-    # MacOS does not support -server flag
-    if [ $darwin = false ]; then
+    "$JAVA" -server -version >/dev/null 2>&1
+    if [ $? -eq 0 ]; then
       JAVA_OPTS="-server $JAVA_OPTS"
     fi
   fi
@@ -154,15 +130,33 @@ if [ $cygwin = false ]; then
   fi
 fi
 
+
+## nuxeo.log.dir
+LOG_DIR=$(grep "^nuxeo.log.dir=" "$NUXEO_CONF" | cut -d= -f2-)
+# Defaults
+: ${LOG_DIR:="$NUXEO_HOME"/log}
+
+
+# For Cygwin, ensure paths are in UNIX format before anything is touched
+if [ "$cygwin" = "true" ]; then
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath -am "$JAVA_HOME"`
+  NUXEO_HOME=`cygpath -am "$NUXEO_HOME"`
+  NUXEO_CONF=`cygpath -am "$NUXEO_CONF"`
+  LOG_DIR=`cygpath -am "$LOG_DIR"`
+fi
+
+
 ## Launcher
 NUXEO_LAUNCHER="$NUXEO_HOME"/bin/nuxeo-launcher.jar
 if [ ! -e "$NUXEO_LAUNCHER" ]; then
-    echo Could not locate $NUXEO_LAUNCHER
-    # echo Please check that you are in the bin directory when running this script.
-    exit 1
+    die "Could not locate $NUXEO_LAUNCHER"
 fi
+
+[ -d "$LOG_DIR" ] || mkdir -p "$LOG_DIR"
+echo "[`date`] Command: $0 $@" >> $LOG_DIR/nuxeoctl.log
 
 #LAUNCHER_DEBUG="-Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=y"
 
-echo Launcher command: $JAVA $LAUNCHER_DEBUG -Dlauncher.java.opts="$JAVA_OPTS" -Dnuxeo.home="$NUXEO_HOME" -Dnuxeo.conf="$NUXEO_CONF" -jar $NUXEO_LAUNCHER $@
-exec "$JAVA" $LAUNCHER_DEBUG -Dlauncher.java.opts="$JAVA_OPTS" -Dnuxeo.home="$NUXEO_HOME" -Dnuxeo.conf="$NUXEO_CONF" -jar "$NUXEO_LAUNCHER" "$@"
+[[ "x$@" =~ -q || "x$@" =~ --quiet ]] || echo Launcher command: $JAVA $LAUNCHER_DEBUG -Dlauncher.java.opts="$JAVA_OPTS" -Dnuxeo.home="$NUXEO_HOME" -Dnuxeo.conf="$NUXEO_CONF" -Dnuxeo.log.dir="$LOG_DIR" -jar $NUXEO_LAUNCHER $@
+echo [`date`] Launcher command: $JAVA $LAUNCHER_DEBUG -Dlauncher.java.opts="$JAVA_OPTS" -Dnuxeo.home="$NUXEO_HOME" -Dnuxeo.conf="$NUXEO_CONF" -Dnuxeo.log.dir="$LOG_DIR" -jar $NUXEO_LAUNCHER $@ >> $LOG_DIR/nuxeoctl.log
+exec "$JAVA" $LAUNCHER_DEBUG -Dlauncher.java.opts="$JAVA_OPTS" -Dnuxeo.home="$NUXEO_HOME" -Dnuxeo.conf="$NUXEO_CONF" -Dnuxeo.log.dir="$LOG_DIR" -jar "$NUXEO_LAUNCHER" "$@"
