NXP-5847: Add missing warn function.

diff --git a/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl b/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
--- a/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
+++ b/nuxeo-distribution-resources/src/main/resources/bin/nuxeoctl
@@ -36,6 +36,18 @@ die() {
 }
 
 
+
+## Helper functions
+warn() {
+  echo "WARNING: $*"
+}
+
+die() {
+  echo "ERROR: $*"
+  exit 1
+}
+
+
 ## OS detection
 cygwin=false
 darwin=false
@@ -45,6 +57,7 @@ case "`uname`" in
   Darwin*) darwin=true;;
   #Linux) linux=true;;
 esac
+
 
 
 ## Setup the JVM (find JAVA_HOME if undefined; use JAVA if defined)
